### PR TITLE
Add the nCine addon

### PR DESCRIPTION
**Pull request by encelo**
I would like to contribute the CATS definitions for the [nCine](https://ncine.github.io/), an open source cross-platform 2D game framework that can be used with both C++ and Lua.

The work took 2-3 weeks of my spare time and gave me the opportunity to review both the C++ Doxygen documentation and the Lua API itself. I would be really glad and proud if it gets accepted as an official addon for the Lua Language Server. 😊

Please don't hesitate to provide feedback and let me know if there is anything that should be changed. 🙏🏻 
GitHub Issue: #191.

### CODE REVIEW

**Comment by encelo** [comment]
The library directory has already passed under the stylua 2.0.1 scrutiny, the only change that it suggests is listing the `ncine.shader.load_from_memory_with_hashes()` function parameters one under the other, but this way the language server complains that: "Annotations specify that a return value si required here." That's why I have reverted that change.

I have updated the PR and the submodule now points to the `addon` branch that does not have `.editorconfig` nor the  `.github/workflows/lua-documentation.yml` files. 👍🏻

**Comment by carsakiller** [comment]
Ok, that is fine.

The submodule actually committed still points to [ff1a7d2](https://github.com/nCine/nCine-LuaCATS/tree/ff1a7d2b354f1ea3c8411c8573f3867e25ac7d66) though. The following should fix it:

1.  `cd` into your addon in your fork of LLS-Addons
2. `git checkout addon`
3. `git pull origin addon`
4. cd back to root of LLS-Addons
5. `git add addons/ncine/module`
6. `git commit -m "fix: point ncine to addon branch"
7. Push the change

**Comment by encelo** [comment]
Thanks for the instructions, it should be fixed now. 👌🏻

**Comment by carsakiller** [comment]
Thank you, nice work!

**Pull request merged**
