### PR TITLE
Added libyue definitions (accidently closed old PR)

### PR DESCRIPTION
**Pull request by Frityet**
[Libyue](https://libyue.com) is a GUI library for C++, JS, and Lua. On the GitHub page, [there is a set of .json files which define the Yue API](https://github.com/yue/yue.github.io/tree/master/docs/latest/lua/api). The [`autogen.lua` file](https://github.com/Frityet/luayue-definitions/blob/generation/autogen.lua) automatically turns that into CATS definitions.

### CODE REVIEW

**Review by carsakiller — CHANGES_REQUESTED** [review]
I think you need to pull the latest changes from `LuaLS:main`, it looks like the PR is removing all the addons that are newer than your local state.

**Comment by carsakiller** [comment]
Make sure you run a `git submodule update` as well.

**Comment by Frityet** [comment]
> I think you need to pull the latest changes from `LuaLS:main`, it looks like the PR is removing all the addons that are newer than your local state.

Oh whoops! thanks

**Comment by Frityet** [comment]
Should be done?

**Comment by carsakiller** [comment]
I am still seeing [lots of edits to other addons](https://github.com/LuaLS/LLS-Addons/pull/46/files). Did you also [update the submodules](https://github.com/LuaLS/LLS-Addons/pull/46#issuecomment-1518669412)?

**Comment by carsakiller** [comment]
@Frityet I have just forced a commit that fixes the submodules issues. It looks like somewhere along the way you lost your `info.json` though. I can't find it in your closed PR, it looks like your changes were completely nuked there.

Please create a new `info.json` and add it to this PR and then we should be good to go 👍

**Comment by carsakiller** [comment]
Correction, now it is fixed. I forgot to actually commit the submodule 🤦‍♂️. Make sure when you add a submodule you use the `git submodule add CLONE_URL addons/NAME/module` command. Also make sure to use the HTTPS clone URL and not just the URL to the GitHub repo HTML page.

**Comment by carsakiller** [comment]
Have you run StyLua yet?

**Comment by Frityet** [comment]
> Have you run StyLua yet?

Sorry was busy with school, I did and it should work now

**Comment by Frityet** [comment]
Is there anything else to be done for this to be merged

**Comment by carsakiller** [comment]
You have not yet committed the update to the submodule that includes the style changes

**Pull request closed without merging**
