### PR TITLE
add Luvit

### PR DESCRIPTION
**Pull request by Bilal2453**

### CODE REVIEW

**Comment by Bilal2453** [comment]
Closes #4

**Comment by carsakiller** [comment]
Hello! Thanks for the contribution!

Please add [an `info.json` file](https://github.com/LuaLS/LLS-Addons/blob/main/addons/love2d/info.json) with a `name` and `description` for your addon. The `size` and `hasPlugin` can be ignored, as those will be automatically generated. Also, please confirm the code follows [StyLua](https://github.com/JohnnyMorganz/StyLua) styling.

[Need to fix the GitHub action](https://github.com/LuaLS/LLS-Addons/pull/5) before this can be merged as well

**Comment by Bilal2453** [comment]
Ah, thought the file would be added by the GitHub action.

**Comment by Bilal2453** [comment]
Oops, rebased one commit more accidentally and that automatically closed the PR. Should be good now I believe.

**Comment by carsakiller** [comment]
Oh boy, now what is wrong with the action? Searching around led me to https://github.com/actions/checkout/issues/455 but I don't think it has trouble with cloning a fork since it looks like it worked for https://github.com/LuaLS/LLS-Addons/pull/5

**Comment by Bilal2453** [comment]
Hm, I can possibly try reopening a new PR to see if the action works there, and if it does we can just close this ignoring this has happened

**Comment by carsakiller** [comment]
Let's try that. Maybe the `ref` is messed up following the rebase?

**Comment by Bilal2453** [comment]
Just in case, I will also do this on a different branch than this `add-luvit` then

**Comment by carsakiller** [comment]
Replaced with https://github.com/LuaLS/LLS-Addons/pull/7

**Pull request closed without merging**
