### PR TITLE
Add MoneyMoney module

### PR DESCRIPTION
**Pull request by lukasbestle**

### CODE REVIEW

**Comment by carsakiller** [comment]
Hello! Thanks for contributing!

Please run [StyLua](https://github.com/JohnnyMorganz/StyLua) to apply the proper code formatting. It is used to keep the style consistent across all definition projects. 🙂

**Comment by lukasbestle** [comment]
@carsakiller Done. ✅
However I think there's something wrong with the GitHub Actions setup in this repo as the workflow already fails in the checkout step.

**Comment by carsakiller** [comment]
Ah, you'd be correct, I believe this is because when I transferred this project into the organization, the token for checking out got removed.

@sumneko I do not have permission to view the tokens for this repo or at the organization level. I guess organizations do not have a default `{ secrets.GITHUB_TOKEN }`?

**Comment by sumneko** [comment]
> @sumneko I do not have permission to view the tokens for this repo or at the organization level. I guess organizations do not have a default `{ secrets.GITHUB_TOKEN }`?

You are right, but why it needs token? This should be a public project

**Comment by carsakiller** [comment]
Yes, but I believe it is needed to prevent rate limiting. The GitHub API rate limits after 60 requests if unauthenticated if I remember correctly.

**Comment by sumneko** [comment]
The doc says
`At the start of each workflow run, GitHub automatically creates a unique GITHUB_TOKEN secret to use in your workflow. You can use the GITHUB_TOKEN to authenticate in a workflow run.`

I don't know how to do it.

**Comment by carsakiller** [comment]
Yeah, that is exactly how it worked before I transferred it. GitHub would automatically create the `GITHUB_TOKEN` for use in the workflow. Now it just immediately panics that there is no token supplied. I am thinking that organizations by default do not have one, as they are not technically a user. Looking at the LuaCATS org, it looks like we have to give explicit permission for the token to work:
image

Although maybe we just have to add our own secret...

**Comment by sumneko** [comment]
> Although maybe we just have to add our own secret...

We can not add secret start with `GITHUB_`

**Comment by lukasbestle** [comment]
I've removed the params for the `checkout` action as they were basically set to their default values anyway. The `GITHUB_TOKEN` is still used for other actions in the workflow, but maybe it brings us closer to what we need.

**Pull request merged**
